---
- name: box setup
  gather_facts: no
  become: yes
  hosts: all
  tasks:
    - block:
        - name: "Add {{ os_username }} group"
          group:
            name: "{{ os_username }}"
            state: present

        - name: "Add {{ os_username }} user"
          user:
            generate_ssh_key: yes
            groups:
              - wheel
              - "{{ os_username }}"
            name: "{{ os_username }}"
            password: "{{ os_password | password_hash('sha256') }}"

        - name: "Allow {{ os_username }} group to have passwordless sudo"
          lineinfile:
            dest: /etc/sudoers
            state: present
            regexp: "^%{{ os_username }}"
            line: "%{{ os_username }} ALL=(ALL) NOPASSWD: ALL"
            validate: visudo -cf %s
      when:
        - os_username is defined
        - os_password is defined
